### ISSUE TITLE
ABORT notifications are not respected if the order already has a successful child transaction

### ISSUE THREAD

**Issue by joshangell** [craftcms/commerce-sagepay#14]
### Description
This only occurs during periods with a high transaction rate as far as I can tell and seems to be due to the behaviour outlined here in the docs: https://developer-eu.elavon.com/docs/opayo-server/taking-payments/step-4-you-confirm-transaction#4b

From that link you can see that if the server running Craft can’t respond within 10 seconds to the success notification then Opayo / SagePay abort the transaction and follow up with an abort notification.

If traffic is high and the server is struggling a bit I’m guessing that it queues the incoming notification requests and responds to them each in turn, once its got the successful notification which has come in first the plugin adds the successful child transaction and the order is completed. Then, because it took longer than 10 seconds in total to respond it processes the abort notification later on but doesn’t do anything with it - instead it writes to the log file.

You can see in the logs that the incoming successful transaction hit first, but the Commerce Webhook controller throws and error because it can’t aquire a lock, this happens on repeat (due to the Opayo retry procedure) until the abort notification comes in.

You can see the relevant code for this plugin here:

```php
if ($successfulPurchaseChildTransaction) {
    Craft::warning('Successful child transaction for “'.$transactionHash.'“ already exists.', 'commerce');
    $url = UrlHelper::actionUrl($transaction->getOrder()->cancelUrl);
    $request->confirm($url);

    exit();
}
```
Source: [src/gateways/Server.php#L139-L145](https://github.com/craftcms/commerce-sagepay/blob/main/src/gateways/Server.php#L139-L145)

The end result is an order that is completed but a payment that has been cancelled at the gateway.

You can replicate this by adding a delay to the top of `processWebHook()` method e.g. `sleep(12)`.

### Additional info

- Craft version: 3.4.27
- PHP version: 7.3
- Database driver & version: MariaDB 10.3
- Plugins & versions: Commerce 3.1.11, SagePay Gateway 2.1.1

Example logs from the site I discovered this on:

```
2021-04-03 10:54:50 [-][-][e0hs4a6usfmid1lb3kigmvlail][error][Exception] Exception: Unable to acquire a lock for transaction: 8342c0XXXXXXXXX in /XXXXXX/vendor/craftcms/commerce/src/services/Webhooks.php:38
Stack trace:
#0 /XXXXXX/vendor/craftcms/commerce/src/controllers/WebhooksController.php(53): craft\commerce\services\Webhooks->processWebhook(Object(craft\commerce\sagepay\gateways\Server))
#1 [internal function]: craft\commerce\controllers\WebhooksController->actionProcessWebhook('4')
#2 /XXXXXX/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /XXXXXX/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /XXXXXX/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('process-webhook', Array)
#5 /XXXXXX/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('process-webhook', Array)
#6 /XXXXXX/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('commerce/webhoo...', Array)
#7 /XXXXXX/vendor/craftcms/cms/src/web/Application.php(559): craft\web\Application->runAction('commerce/webhoo...', Array)
#8 /XXXXXX/vendor/craftcms/cms/src/web/Application.php(270): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#9 /XXXXXX/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#10 /XXXXXX/web/index.php(21): yii\base\Application->run()
#11 {main}
2021-04-03 10:54:45 [-][-][e0hs4a6usfmid1lb3kigmvlail][info][application] $_GET = [
    'gateway' => '4'
    'commerceTransactionHash' => '8342c0XXXXXXXXX'
]

$_POST = [
    'VPSProtocol' => '3.00'
    'TxType' => 'PAYMENT'
    'VendorTxCode' => '8342c0XXXXXXXXX'
    'VPSTxId' => '{XXXXXXXXX}'
    'Status' => 'OK'
    'StatusDetail' => '0000 : The Authorisation was Successful.'
    'TxAuthNo' => 'XXXXXXX'
    'AVSCV2' => 'ALL MATCH'
    'AddressResult' => 'MATCHED'
    'PostCodeResult' => 'MATCHED'
    'CV2Result' => 'MATCHED'
    'GiftAid' => '0'
    '3DSecureStatus' => 'NOTCHECKED'
    'CardType' => 'DELTA'
    'Last4Digits' => 'XXXX'
    'VPSSignature' => 'XXXXXXX'
    'DeclineCode' => '00'
    'ExpiryDate' => 'XXXX'
    'BankAuthCode' => 'XXXXXX'
]

$_FILES = []

$_COOKIE = []

$_SESSION = [
    'bd62416aa8538ede709019a5e113eea5__flash' => []
    'commerce_customer' => 3099180
    'commerce_cart' => 'f127e07XXXXXXXXXXXXXXXX'
]

$_SERVER = [
    'USER' => 'XXX'
    'HOME' => '/XXX/XXX'
    'HTTP_CONTENT_LENGTH' => '458'
    'HTTP_CONNECTION' => 'keep-alive'
    'HTTP_ACCEPT' => 'text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2'
    'HTTP_HOST' => 'XXXXXX.co.uk'
    'HTTP_PRAGMA' => 'no-cache'
    'HTTP_CACHE_CONTROL' => 'no-cache'
    'HTTP_CONTENT_TYPE' => 'application/x-www-form-urlencoded'
    'HTTP_USER_AGENT' => 'SagePay-Notifier/1.0'
    'REDIRECT_STATUS' => '200'
    'HTTPS' => 'on'
    'SERVER_NAME' => 'XXXXXX.co.uk'
    'SERVER_PORT' => '443'
    'SERVER_ADDR' => 'XXX.XXX.XXX.XXX'
    'REMOTE_PORT' => '1075'
    'REMOTE_ADDR' => 'XXX.XXX.XXX.XXX'
    'SERVER_SOFTWARE' => 'nginx/1.18.0'
    'GATEWAY_INTERFACE' => 'CGI/1.1'
    'SERVER_PROTOCOL' => 'HTTP/1.1'
    'DOCUMENT_ROOT' => '/XXXXXX/web'
    'DOCUMENT_URI' => '/index.php'
    'REQUEST_URI' => '/index.php/actions/commerce/webhooks/process-webhook?gateway=4&commerceTransactionHash=8342c0XXXXXXXXX'
    'SCRIPT_NAME' => '/index.php'
    'SCRIPT_FILENAME' => '/XXXXXX/web/index.php'
    'CONTENT_LENGTH' => '458'
    'CONTENT_TYPE' => 'application/x-www-form-urlencoded'
    'REQUEST_METHOD' => 'POST'
    'QUERY_STRING' => 'gateway=4&commerceTransactionHash=8342c0XXXXXXXXX'
    'FCGI_ROLE' => 'RESPONDER'
    'PHP_SELF' => '/index.php'
    'REQUEST_TIME_FLOAT' => 1617443685.6069
    'REQUEST_TIME' => 1617443685
    'ENVIRONMENT' => 'production'
    'SECURITY_KEY' => '••••••••••••••••••••••••••••••••'
    'DB_DRIVER' => 'mysql'
    'DB_DSN' => 'mysql:host=127.0.0.1;port=3306;dbname=production'
    'DB_USER' => 'XXX'
    'DB_PASSWORD' => '••••••••••••••••••••'
    'DB_SCHEMA' => 'public'
    'DB_TABLE_PREFIX' => 'craft'
]
2021-04-03 11:22:07 [-][-][-][warning][commerce] Successful child transaction for “8342c0XXXXXXXXX“ already exists.
2021-04-03 11:22:07 [-][-][-][info][application] $_GET = [
    'gateway' => '4'
    'commerceTransactionHash' => '8342c0XXXXXXXXX'
]

$_POST = [
    'VPSProtocol' => '3.00'
    'TxType' => 'PAYMENT'
    'VendorTxCode' => '8342c0XXXXXXXXX'
    'VPSTxId' => '{XXXXXXXXX}'
    'Status' => 'ABORT'
    'StatusDetail' => '2008 : The Transaction timed-out.'
    'TxAuthNo' => 'XXXXXXX'
    'AVSCV2' => 'ALL MATCH'
    'AddressResult' => 'MATCHED'
    'PostCodeResult' => 'MATCHED'
    'CV2Result' => 'MATCHED'
    'GiftAid' => '0'
    '3DSecureStatus' => 'NOTCHECKED'
    'CardType' => 'DELTA'
    'Last4Digits' => 'XXXX'
    'VPSSignature' => 'XXXXXXXXXXXXXX'
    'DeclineCode' => '00'
    'ExpiryDate' => 'XXXX'
    'BankAuthCode' => 'XXXXXX'
]

$_FILES = []

$_COOKIE = []

$_SERVER = [
    'USER' => 'XXX'
    'HOME' => '/XXX/XXX'
    'HTTP_CONTENT_LENGTH' => '454'
    'HTTP_CONNECTION' => 'keep-alive'
    'HTTP_ACCEPT' => 'text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2'
    'HTTP_HOST' => 'XXXXXX.co.uk'
    'HTTP_PRAGMA' => 'no-cache'
    'HTTP_CACHE_CONTROL' => 'no-cache'
    'HTTP_CONTENT_TYPE' => 'application/x-www-form-urlencoded'
    'HTTP_USER_AGENT' => 'SagePay-Notifier/1.0'
    'REDIRECT_STATUS' => '200'
    'HTTPS' => 'on'
    'SERVER_NAME' => 'XXXXXX.co.uk'
    'SERVER_PORT' => '443'
    'SERVER_ADDR' => 'XXX.XXX.XXX.XXX'
    'REMOTE_PORT' => '37762'
    'REMOTE_ADDR' => 'XXX.XXX.XXX.XXX'
    'SERVER_SOFTWARE' => 'nginx/1.18.0'
    'GATEWAY_INTERFACE' => 'CGI/1.1'
    'SERVER_PROTOCOL' => 'HTTP/1.1'
    'DOCUMENT_ROOT' => '/XXXXXX/web'
    'DOCUMENT_URI' => '/index.php'
    'REQUEST_URI' => '/index.php/actions/commerce/webhooks/process-webhook?gateway=4&commerceTransactionHash=8342c0XXXXXXXXX'
    'SCRIPT_NAME' => '/index.php'
    'SCRIPT_FILENAME' => '/XXXXXX/web/index.php'
    'CONTENT_LENGTH' => '454'
    'CONTENT_TYPE' => 'application/x-www-form-urlencoded'
    'REQUEST_METHOD' => 'POST'
    'QUERY_STRING' => 'gateway=4&commerceTransactionHash=8342c0XXXXXXXXX'
    'FCGI_ROLE' => 'RESPONDER'
    'PHP_SELF' => '/index.php'
    'REQUEST_TIME_FLOAT' => 1617445327.3318
    'REQUEST_TIME' => 1617445327
    'ENVIRONMENT' => 'production'
    'SECURITY_KEY' => '••••••••••••••••••••••••••••••••'
    'DB_DRIVER' => 'mysql'
    'DB_DSN' => 'mysql:host=127.0.0.1;port=3306;dbname=production'
    'DB_USER' => 'XXX'
    'DB_PASSWORD' => '••••••••••••••••••••'
    'DB_SCHEMA' => 'public'
    'DB_TABLE_PREFIX' => 'craft'
]
```

**Comment by nfourtythree** [comment]
Hi @joshangell 

Thank you for bringing this to our attention.

We have spent some time looking into this, discussing and testing this out.

The way that SagePay deals with timeouts/long server loads is certainly a little odd. Instead of waiting for longer they actually make more requests which seems slightly counter-intuitive but obviously, this is out of all of our control.

Testing the processing of an "abort" webhook being processed in isolation does correctly mark a transaction as failed which is good news, but means that the issue lays elsewhere.

I have [pushed up a commit]() that might help with the situation. Although we don't think this is what you are seeing we did notice that potentially a mutex lock was not being released correctly.

On to the testing and findings. As we can see from the SagePay docs if the server takes too long to respond they will send further requests. What this means in terms of the Commerce code is that when the first initial webhook is being processed a mutex lock is created (this is done to prevent duplicate transactions being registered, looking like an order has been overpaid). 

If this process takes a long time SagePay will then fire off another request, this request will likely timeout/be returned with an error as it will be unable to acquire a lock due to the first request not releasing it. This will continue to happen until the lock is released or SagePay stops sending request.

What I did see in testing is that as long as there is a response to the first request before SagePay stops sending the repeat requests everything goes through fine, payment is complete and the user sent to the success page. This can be seen in the following screenshot: 

![](https://p191.p3.n0.cdn.getcloudapp.com/items/o0u69goJ/cc9e1445-c2bc-4393-8acb-50eadde025d5.png?v=1544707ff704fb3fe63b4b8c5f6f7f83)

To explain the screenshot:

- 1 is the initial request, I paused this to simulate a long load time
- Request 2 is made after a certain period of time (after about 20 seconds), this errors out due to mutex lock
- After request 2 errors out request 3 is made straight away, I let this fail with a mutex lock error as before
- At this point, I unpaused request 1, this request finished successfully
- This meant when request 4 came in the code processed found out that there was a successful transaction already and returned SagePay the appropriate data
- SagePay then redirect me to the site as you can see in requests 5 and 5a

As mentioned before, it seems as long as you can respond in those 9 requests everything should be fine. This, realistically, points me to look at how the server could be taking a really long time to respond. There isn't anything particularly taxing in that code path that we would see causes for minutes worth of response time and as you can see from the screenshot working within a minute or so is plenty enough time to has a successful response to SagePay.

One other thing to note is that there isn't really a straight forward way for us to check on the status of a transaction in the middle of that process (which is what we do in other gateways). Also, if this issue is related to timings and slow processing adding another back and forth with SagePay would seem like it may add to the problem rather than solve it.

As a last side note, unlike the docs state in testing the "abort" webhook call didn't seem to be called until much later, 10 minutes in some cases. But, I obviously am not sure if this is just a sandbox issue.

Happy to hear your thoughts on this and it maybe worth trying the new code to see if it improves things.

You can do this by, changing your `craftcms/commerce-sagepay` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce-sagepay": "dev-develop#4407c53a46a103567dce36e2df281d5b42534519 as 3.0.0",
  "...": "..."
}
```

Then run `composer update`.

**Comment by joshangell** [comment]
Hey Nathanial, thanks for having a stab at this - sorry its taken me a while to run the updates at our end, we had to upgrade to  3.6 from 3.4 etc etc etc haha - anyway, I have it up and running now and will check once a week for the next month or so to see if we get any more escaping orders.

I’ll update this issue either if I get a bad one or if after a month nothing has happened - at which point I’d be happy to consider it mysteriously fixed 😂 

Also, on your last point we have noticed the same in production - sometimes it does take a while for the ABORT webhook call to come in, who knows why ¯\_(ツ)_/¯

Either way - thanks and I’ll update you in due course!

**Comment by nfourtythree** [comment]
Hi @joshangell 

Any feedback to report on this one?

Thanks.

**Comment by joshangell** [comment]
So far so good! I’ve been monitoring the logs once a week for the past month and nothing has come up, I’ll do another check later today / tomorrow and if that comes back clean then I think we can conclude this has worked ... or the issue has just gone away!

**Comment by nfourtythree** [comment]
@joshangell Everything all good?

**Comment by joshangell** [comment]
Sorry been silly busy - just did a final check now and its not looking good, had one on the 17th and then 5 more on the 18th - before the 17th I hadn’t had any since patching it. I’m not really sure what we should be looking at to fix this though ...
